[package]
name = "rpmmake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocipkg = "0.2.8"
anyhow = "1.0.66"
vfs = "0.7.1"
libmount = "0.1.15"
tempdir = "0.3.7"